security:
    providers:
        mysql_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            form_login: 
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: home
            provider: mysql_db_provider
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/network/element/admin, roles:[ROLE_ADMIN] }
        - { path: ^/network/element/type/admin, roles:[ROLE_ADMIN] }
        - { path: ^/vendor/admin, roles:[ROLE_ADMIN] }
        - { path: ^/vendor, roles:[ROLE_PLANNING] }
        - { path: ^/network/element, roles:[ROLE_GUEST] }
        - { path: ^/erlangb, roles:[ROLE_PLANNING,ROLE_USER] }
        - { path: ^/erlangb, roles:[ROLE_PLANNING] }
        - { path: ^/feasibility, roles:[ROLE_PLANNING,ROLE_B2B] }
        - { path: ^/rgn, roles:[ROLE_PLANNING] }
        - { path: ^/user, roles:[ROLE_PLANNING,ROLE_B2B,ROLE_USER] }
        - { path: ^/home, roles:[ROLE_PLANNING,ROLE_B2B,ROLE_USER,ROLE_GUEST] }

        #- { path: ^/,roles:[ROLE_USER,ROLE_PLANNING,ROLE_B2B]}
        #- { path: ^/admin, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_B2B,ROLE_PLANNING,ROLE_GUEST]
        ROLE_PLANNING:    [ROLE_GUEST]
        